### ISSUE TITLE
Cannot detect difference between one modifier and both left and right modifiers

### ISSUE THREAD

**Issue by es183923** [knu/hs-knu#1]
With the following code, the only output will be `leftshift+rightshift-a`, and never `rightshift`.  Could you fix this?

```lua
knu.photkey.bind({"rightshift"}, "a", function ()
    hs.eventtap.keyStrokes("rightshift-a\n")
end)
knu.photkey.bind({"leftshift", "rightshift"}, "a", function ()
    hs.eventtap.keyStrokes("leftshift+rightshift-a\n")
end)
```

**Comment by knu** [comment]
You are right.  The photkey module currently does not support the left+shift combination of a modifier.  I'll try to fix it.
